version: '3'
services:
  db:
    image: mysql:5.6.47
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  web:
    build: .
    volumes:
      - .:/blog_app
    command: /bin/sh -c "rm -f /workdir/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    depends_on:
      - db
