version: 2.1
orbs:
  ruby-orbs: sue445/ruby-orbs@1.6.0
  heroku: circleci/heroku@1.0.1

workflows:
   test_and_deploy:
    jobs:
      - test
      - deploy_prd:
          requires:
            - test
          filters:
            branches:
              only:
                - master

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          BUNDLER_VERSION: 2.1.4

jobs:
  test:
    executor: default
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler -v 2.1.4
            bundle install
      - run:
          name: rubocop
          command: |
            bundle exec rubocop
      # 以下はRails6でWebpackerを使う場合は必須   
      - restore_cache:  
          keys:  
            - yarn-cache-v1-{{ checksum "yarn.lock" }}  
            - yarn-cache-v1-  

      - run:  
          name: Yarn Install  
          command: yarn install --cache-folder ~/.cache/yarn  

      - save_cache:  
          key: yarn-cache-v1-{{ checksum "yarn.lock" }}  
          paths:  
            - ~/.cache/yarn  
      - run: 
          name: rspec
          command: |
            bundle exec rspec
  deploy_prd:
    executor: heroku/default
    parameters:
      app-name: 
        default: $HEROKU_APP_NAME_PRD
        type: string
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: << parameters.app-name >>
      - run:
          name: migrate
          command: |
            heroku run rails db:migrate --app $HEROKU_APP_NAME_PRD
